### PR TITLE
290: assure that uploaded files show up in existing files list after save

### LINKED ISSUE #290: Applicant is able to upload but not save a document on the PAS Form
[AB#10532](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10532)

## Browser(s) and Device(s) observed on:
Chrome, IE, Firefox

## What should happen:
User should be able to upload and save documents on the PAS Form, in the Attached Documents Section

## What happened instead:
Applicant is able to upload but not save a document on the PAS Form
## How to reproduce this bug:

1. Log into the Applicant Portal
2. Click on the Edit Pre-Application Statement Button
3. Navigate to the Attached Documents Section 
4. click on the choose files
5. select a file and save (after saving document disappears)

image

After Saving 

image

### PR DESCRIPTION
**Pull request by trbmcginnis**
Previously, because `existingFiles` is only loaded once when the fileManager is instantiated, the `existingFiles` array was not being updated (and therefore not displaying) the recently uploaded files after the user had clicked save. They would only display when a user refreshed. This PR assures that the uploaded file objects are pushed to the `existingFiles` array so that they show in the UI. 

Screen Shot 2020-05-29 at 12 49 38 AM

`pas-form-error` component was also updated to account for package errors, since `documents` exist as an attribute on the package model rather than the PAS Form model.

Closes #290

### CODE REVIEW

File: client/app/services/file-manager.js [hunk 1]
```diff
@@ -59,6 +54,7 @@ export default class FileManager {
   }
 
   uploadFiles() {
+    this.filesToUpload.files.forEach((file) => this.existingFiles.pushObject(file));
```
Comment (allthesignals) [inline client/app/services/file-manager.js:57]: Nice!

What if the file uploads fail? What if we `await` the Promse.all on the line below, wrapped in a try / catch, then say:

```
this.existingFiles.pushObjects(this.filesToUpload.files)
```

Comment (godfreyyeung) [inline client/app/services/file-manager.js:57]: The files won't have an actual link here, though. They don't look like these will be actual "uploaded files"

Comment (godfreyyeung) [reply client/app/services/file-manager.js:57]: Jotting pseudocode down from our engineering standup:

models/package.js
```
  refreshFileQueue() {
    this.fileManager.existingFiles = this.documents;
  }
```

components/packages/pas-form/edit.js
```
  @action
  async savePackage() {
    await this.args.package.save();
    await this.args.package.reload();
    this.args.package.refreshFileQueue();
  }
```

Comment (trbmcginnis) [reply client/app/services/file-manager.js:57]: Thanks, I'll try that!

Comment (godfreyyeung) [reply client/app/services/file-manager.js:57]: The `refreshFileQueue` name was totally wrong... since it's refreshing existing documents. 🙈  I updated it to another possibility. This is all just draft. You have the final call!

File: client/app/components/packages/pas-form-error.hbs [hunk 2]
```diff
@@ -8,8 +8,11 @@
       />
         There was a problem saving your information.
     </h5>
-      {{#each @pasForm.adapterError.errors as |error|}}
-        <p class="font-mono text-red-dark bg-red-white small-padding text-small" data-test-error-message>{{error.details}}</p>
+      {{#each @package.pasForm.adapterError.errors as |error|}}
+        <p class="font-mono text-red-dark bg-red-white small-padding text-small" data-test-error-message>{{error.detail}}</p>
+      {{/each}}
```
Comment (allthesignals) [inline client/app/components/packages/pas-form-error.hbs:13]: Good

File: client/app/components/packages/pas-form/edit.js [hunk 3]
```diff
@@ -30,7 +30,14 @@ export default class PasFormComponent extends Component {
...
   async savePackage() {
-    await this.args.package.save();
+    try {
+      await this.args.package.save();
+      await this.args.package.reload();
+    } catch (error) {
+      console.log('Save package error:', error);
+    }
+
+    this.args.package.refreshExistingDocuments();
```
Comment (allthesignals) [inline client/app/components/packages/pas-form/edit.js:40]: I think this works for now, but I'm beginning to think that these documents should be their own model now. This line here is a sign that we're sort of having to manually manage the state of documents. Right? For example, when we have docs queued up for upload, those are "dirty" in a way, we can show those as such. When they save, their "clean", they've saved, we can show those accordingly.

I think a refactor task should be to seriously re-think doc upload and embrace Ember Data for them.

Comment (trbmcginnis) [reply client/app/components/packages/pas-form/edit.js:40]: That makes a lot of sense -- I'm going to go ahead and merge this for the sake of the end of the sprint and then I'll be sure to make an issue addressing this, thanks!
